declare global {
  interface Env {
    APP_BASE_URL?: string;
    CLASSIFICATION_PROVIDER?: string;
    DISCORD_PROCESSING_FAILURE_WEBHOOK_URL?: string;
    OPENROUTER_CLASSIFICATION_FALLBACK_MODEL?: string;
    OPENROUTER_CLASSIFICATION_MODEL?: string;
    TRANSCRIPTION_GATEWAY_URL: string;
    TRANSCRIPTION_GATEWAY_TOKEN?: string;
    OPENROUTER_API_KEY: string;
    PROCESSING_QUEUE: Queue;
  }
}

export {};
